name: Run unit tests
on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python v3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
    - name: Run tests and generate coverage report
      run: |
        python -m unittest -v
        coverage run -m unittest
        coverage report